/* eslint-disable react/jsx-one-expression-per-line */
/* eslint-disable max-len */
import React from 'react';
import {
  Grid, Container, Typography, Breadcrumbs, Link,
} from '@material-ui/core';
import styles from './styles';

function AboutUs() {
  const classes = styles();


  return (
    <div className={classes.initContainer}>
      <Container>
        <Grid
          item
          xs={12}
          className={classes.grid}
        >
          <Breadcrumbs aria-label="breadcrumb">
            <Link color="inherit" href="/">
              Home
            </Link>
            <Typography color="textPrimary">About us</Typography>
          </Breadcrumbs>
          <Typography
            gutterBottom
            className={classes.textFormat}
            variant="overline"
            component="h2"
          >
            THE LABORATÓRIO INTERINSTITUCIONAL DE E-ASTRONOMIA (LINEA) WAS CREATED IN NOVEMBER 2010 BY AN AGREEMENT SIGNED BY THREE RESEARCH INSTITUTES OF THE MINISTRY OF SCIENCE, TECHNOLOGY, INNOVATION AND COMMUNICATION (MCTIC) (LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA, OBSERVATÓRIO NACIONAL,  E  REDE NACIONAL DE ENSINO E PESQUISA) TO PROVIDE SUPPORT FOR THE PARTICIPATION OF BRAZILIAN SCIENTISTS IN LARGE INTERNATIONAL PROGRAMS REQUIRING AN IT INFRASTRUCTURE SUCH AS SDSS, DES, DESI AND LSST. SOME OF ITS MAIN PROJECTS INCLUDE:
            <ul>
              <li>THE QUICK REDUCE PIPELINE AVAILABLE AT CTIO TO ASSESS THE QUALITY OF THE IMAGES GATHERED BY DECAM;<br />THE SCIENCE PORTAL, A COMPREHENSIVE INTEGRATED WEB-BASED END-TO-END SYSTEM TO STREAMLINE THE PRODUCTION OF ANCILLARY INFORMATION USED TO CREATE VALUE-ADDED SCIENCE READY CATALOG TO FEED A VARIETY OF SCIENCE ANALYSIS WORKFLOWS;</li>
              <li>THE DATA SERVER INTERFACE AVAILABLE AT FERMILAB SINCE APRIL 2014 TO ENABLE THE VISUALIZATION OF IMAGES AND OBJECTS, AND TO CARRY OUT QUERIES IN THE DESDM DATABASE. THE INTERFACE HAS BEEN ACCESSED 4500 TIMES OVER THE PAST THREE YEARS BY 250 USERS;</li>
              <li>THE QUICK LOOK FRAMEWORK (QLF) BEING DEVELOPED TO ASSESS THE QUALITY OF THE 15,000 SPECTRA OF THE 5,000 OBJECTS TO BE OBSERVED IN EACH EXPOSURE OF DESI.<br />THE LINEA SCIENCE SERVER BEING MADE AVAILABLE AT NCSA AND WHICH WILL BE USED AS ONE OF THE INTERFACES OF THE DES DATA RELEASE DR1.</li>
              <li>IN ADDITION, LINEA MAINTAINS A DATA CENTER (1000 CORES PROCESSING CLUSTER, 1 PB MASS STORAGE AND A HOST OF OTHER MACHINES) FOR ITS AFFILIATES, CURRENTLY AROUND 80 MEMBERS, A MIRROR SITE FOR SDSS PROVIDING INDEPENDENT SKYSERVER AND CASJOBS SERVICES, AND PROVIDES SUPPORT TO THE COMPUTER INFRASTRUCTURE BEING USED BY THE APOGEE-2 PROJECT AT THE LAS CAMPANAS OBSERVATORY.</li>
            </ul>
          </Typography>
        </Grid>
      </Container>
    </div>
  );
}

export default AboutUs;
